# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Start of steps
    steps:
    
    # Checks out your repo so it can be accessed by job.
     - name: Checkout branch from GitHub
       uses: actions/checkout@v2
       
    # Runners fetch and install Java.   
     - name: Set up JDK 18
       uses: actions/setup-java@v3.4.1
       with:
          java-version: '18'
          distribution: 'adopt'
    
    # Building Project
     - name: Build with Maven
       run: mvn -B package --file pom.xml
    
    # Testing Project   
     - name: Test
       run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
    
    # File Manager
     - name: Listing files in directory
       run: ls -a
    
     - name: What is the target folder? 
       run: |
        cd target
        ls -a
    
    # Caching to reduce load and latency on GitHub workflow. 
     - name: Cache
       uses: actions/cache@v3.0.5
       with:
        path: .m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
